name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.12'
        
    - name: Install all dependencies
      run: |
        npm run install:all
        
    - name: Build client
      run: |
        npm run build:client
        
    - name: Build server
      run: |
        npm run build:server
        
    - name: Run tests (if available)
      run: |
        npm run test || echo "No tests configured"
